import requests
import json
import time

BASE_URL = "http://127.0.0.1:5000"
API_KEY = "" # Will be set after registration

def print_response(title, response):
    print(f"\n--- {title} ---")
    print(f"Status Code: {response.status_code}")
    try:
        print(f"Response: {json.dumps(response.json(), indent=2)}")
    except requests.exceptions.JSONDecodeError:
        print(f"Response (non-JSON): {response.text}")
    print("-" * (len(title) + 8))

def run_tests():
    global API_KEY
    print("Starting automated API tests for AI Agent Forum...\n")

    # --- 1. Agent Registration ---
    print("Attempting to register TesterBot...")
    try:
        register_url = f"{BASE_URL}/api/agents/register"
        response = requests.post(register_url, json={"name": "TesterBot"})
        print_response("Agent Registration", response)
        if response.status_code == 201:
            API_KEY = response.json()['api_key']
            print(f"TesterBot registered successfully. API Key: {API_KEY}")
        elif response.status_code == 400 and "already exists" in response.json().get('message', ''):
            print("TesterBot already exists. Skipping registration.")
            # If agent already exists, we cannot get its API key via this endpoint.
            # For a real system, there would be an agent login/retrieve API key endpoint.
            # For this prototype, we'll ask the user to manually provide if needed, or assume it's set.
            # For now, let's assume if it exists, a human registered it and we don't have its API key automatically.
            # If you re-run this script after a fresh DB, you'll get a new key.
            # For testing, delete site.db and restart app before running this script for a clean run.
            print("Please ensure you've deleted site.db and restarted the app for a clean run if you wish to get a new API Key.")
            print("If TesterBot previously registered, its API key won't be automatically retrieved here.")
            return # Stop if cannot register and get API key

    except requests.exceptions.ConnectionError:
        print("Error: Could not connect to the Flask application. Is it running?")
        return
    except Exception as e:
        print(f"An unexpected error occurred during registration: {e}")
        return

    if not API_KEY:
        print("\n--- ERROR ---")
        print("Failed to get API_KEY. Cannot proceed with further tests.")
        print("Please ensure the app is running and TesterBot registration was successful.")
        return

    headers = {"X-API-KEY": API_KEY}
    post_id = None
    comment_id = None
    reply_comment_id = None

    # --- 2. Create a Post ---
    print("\nAttempting to create a post...")
    post_data = {
        "title": "Automated Test Post: AI Forum Exploration",
        "content": "This post is generated by TesterBot to explore the functionality of the AI Agent Forum. Automated testing in progress!"
    }
    response = requests.post(f"{BASE_URL}/api/posts", headers=headers, json=post_data)
    print_response("Create Post", response)
    if response.status_code == 201:
        post_id = response.json()['post_id']
        print(f"Post created successfully with ID: {post_id}")
    else:
        print("Failed to create post. Aborting further tests.")
        return
    time.sleep(0.5) # Give DB a moment

    # --- 3. Vote on the Post (Upvote) ---
    print(f"\nAttempting to upvote Post ID: {post_id}...")
    vote_data = {"type": "upvote"}
    response = requests.post(f"{BASE_URL}/api/posts/{post_id}/vote", headers=headers, json=vote_data)
    print_response("Upvote Post", response)
    time.sleep(0.5)

    # --- 4. Create a Comment ---
    print(f"\nAttempting to create a comment on Post ID: {post_id}...")
    comment_data = {"content": "This is a top-level automated comment from TesterBot."}
    response = requests.post(f"{BASE_URL}/api/posts/{post_id}/comments", headers=headers, json=comment_data)
    print_response("Create Comment", response)
    if response.status_code == 201:
        comment_id = response.json()['comment_id']
        print(f"Comment created successfully with ID: {comment_id}")
    time.sleep(0.5)

    # --- 5. Vote on the Comment (Upvote) ---
    if comment_id:
        print(f"\nAttempting to upvote Comment ID: {comment_id}...")
        vote_data = {"type": "upvote"}
        response = requests.post(f"{BASE_URL}/api/comments/{comment_id}/vote", headers=headers, json=vote_data)
        print_response("Upvote Comment", response)
        time.sleep(0.5)

    # --- 6. Create a Reply to the Comment ---
    if post_id and comment_id:
        print(f"\nAttempting to create a reply to Comment ID: {comment_id} on Post ID: {post_id}...")
        reply_data = {"content": "This is an automated reply, demonstrating nested comments!", "parent_comment_id": comment_id}
        response = requests.post(f"{BASE_URL}/api/posts/{post_id}/comments", headers=headers, json=reply_data)
        print_response("Create Reply", response)
        if response.status_code == 201:
            reply_comment_id = response.json()['comment_id']
            print(f"Reply created successfully with ID: {reply_comment_id}")
        time.sleep(0.5)

    # --- 7. Test Pagination: Get All Posts ---
    print("\n--- Testing Pagination: Get All Posts ---")
    endpoints_to_test = [
        (f"{BASE_URL}/api/posts?limit=1&offset=0", "All Posts (Limit 1, Offset 0)"),
        (f"{BASE_URL}/api/posts?limit=1&offset=1", "All Posts (Limit 1, Offset 1)"),
        (f"{BASE_URL}/api/posts/trending?limit=1&offset=0", "Trending (Limit 1, Offset 0)"),
        (f"{BASE_URL}/api/search?q=Automated&limit=1&offset=0", "Search (Limit 1, Offset 0, Query 'Automated')")
    ]
    for url, description in endpoints_to_test:
        print(f"\nFetching: {description}")
        response = requests.get(url, headers=headers) # Headers for consistency, though not required for GET
        print_response(description, response)
        time.sleep(0.5)

    # --- 8. Verify Post Details (including votes and nested comments) ---
    if post_id:
        print(f"\n--- Verifying Post Details for Post ID: {post_id} ---")
        response = requests.get(f"{BASE_URL}/api/posts/{post_id}", headers=headers)
        print_response("Post Details Verification", response)
    
    print("\nAutomated API tests completed.")

if __name__ == "__main__":
    run_tests()
